import { Open_Sans } from 'next/font/google';

import type { Metadata } from 'next';

import './globals.css';

import { ReactQueryProvider } from '@/utils/providers';

import { Footer } from '@/components/Footer/Footer';
import { Navbar } from '@/components/Navbar/Navbar';

const globalFont = Open_Sans({
  variable: '--font-global',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${globalFont.variable} font-global antialiased`}>
        <div className="min-h-svh md:min-h-screen">
          <ReactQueryProvider>
            <Navbar />
            <main>{children}</main>
            <Footer />
          </ReactQueryProvider>
        </div>
      </body>
    </html>
  );
}
